@startuml overview

class Engine {
    +setUpBoard()
    +handleInput()
    -generateOutput()
}

class SequentialProbabilityRatioTest {
    +evaluate()
}
class Bot {
    +updateSettings()
    +getBestMove()
    -tryOpeningBook()
    -tryTablebase()
}
class Board {
    +makeMove()
    +unmakeMove()
    +loadBoardPosition()
    -isInCheck()
    -isInCheckMate()
    -isGameOver()
}

class BitBoardUtil {
    +getPieceType()
}
class Move {
    -startPos
    -endPos
    +getStartPos()
    +getEndPos()
}

class Searcher {
    -currBestMove
    -timer
    +search()
}
Class Evaluator {
    +evaluate()
}
class MoveGenerator {
    +generateMoves()
}

abstract class Database {
    -database
    +lookUp()
}
class OpeningBook extends Database
class Tablebase extends Database

SequentialProbabilityRatioTest <-right- Engine
Engine *-- Board
Engine *-- Bot

Board <-- BitBoardUtil
Board <-- Move

Bot *-- Database
Bot *-- Searcher
Bot <-right- Board

'Database *-- OpeningBook
'Database *-- Tablebase

Searcher *-- Evaluator
Searcher *-- MoveGenerator

@enduml